---
title:  Intro to Conjoint Experiments | Exercise - 2
author: Alberto Stefanelli
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_dir = "html") })
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    use_bookdown: true
    fig_width: 12
    fig_height: 8
  #html_document:
    #theme: rmdformats
    # df_print: paged
    # toc: true
    # number_sections: true
    # toc_float:
    #   collapsed: false
    #   smooth_scroll: false
---
<style type="text/css">
#content {
    max-width: 1500px !important;
/*    !margin-left: 300px !important;
*/
}
#table-of-contents {
    width: 300px !important;
}

#postamble {
  font-size: 10px;
}

pre{
  background-color: #FFFFFF;
    font-size: 12px;
}
pre:not([class]) {
  background-color: #D8D8D8;
    color: black;
}

</style>

```{r global_options, include=FALSE}
knitr::opts_chunk$set(tidy=FALSE, 
  fig.show = 'hold', 
  fig.align = "center", 
  warning = FALSE, 
  message = FALSE, 
  comment = '')
options(width = 300, scipen = 9999)

# last dev version is needed for rmdformats.
# fixed these two
# more info https://github.com/juba/rmdformats/issues/92 
# more info https://github.com/juba/rmdformats/issues/93
# devtools::install_github("juba/rmdformats")

```

  
# Build a CJ Design 

You will be divided in groups and asked to design an CJ experiment. We will implement the design in qualtrics in the next session. 

Must be:

1. Interesting RQ to a broader public 
2. You should produce something that has empirical value (although not necessary academic)
3. It should be in English and focus on the US so that we can collect responses from /r/samplesize 

**Guidelines:**

1. What is my RQ (and hypotheses) ? 
    - Literature is relevant
    - Use previous knowledge and avoid 'shooting in the dark'
    - However, it can be exploratory 
2. Basic design choices: 
    - Select the attributes
    - Select the levels 
    - Framing/priming [we will implement this on Qualtrics]
3. Other design choices: 
    - Uniform or non-uniform distribution?
    - Restrictions on combination of certain attributes/levels (please include if necessary)
    - Attribute order constrains?
    - How many profiles per choice-sets? (let's stick to two unless specific needs)
    - How many comparisons to include (sample size)?



